name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ruff
        run: python -m ruff check .

      - name: Run pytest
        env:
          # Optionally provide GOOGLE_API_KEY via repository secrets if you want
          # external tests to run. Leave blank to skip tests marked as external.
          GOOGLE_API_KEY: '${{ secrets.GOOGLE_API_KEY }}'
        run: python -m pytest -q
